version: "3.7"

services:
  db:
    image: "mysql:5.7"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: projet-examen
      MYSQL_USER: admin
      MYSQL_PASSWORD: root
    ports:
      - 3306:3306

  php-server1:
    build: "./php/"
    volumes:
      - "./db_data:/var/www/html/"
    ports:
      - 9000
    depends_on:
      - db

  php-server2:
    build: "./php/"
    ports:
      - 9000
    volumes:
      - "./db_data2:/var/www/html/"
    depends_on:
      - db

  nginx-1:
    build:
      context: ./nginx/
      args:
        - FILE_NAME=conf-nginx1.conf
    ports:
      - 81:80
    volumes:
      - "./db_data:/var/www/html/"
    depends_on:
      - db

  nginx-2:
    build:
      context: ./nginx/
      args:
        - FILE_NAME=conf-nginx2.conf
    ports:
      - 82:80
    volumes:
      - "./db_data2:/var/www/html/"
    depends_on:
      - db

  # composer:
  #   image: "composer"
  #   ports:
  #     - "9001:9000"
  #   volumes:
  #     - "./db_data:/var/www/html/"
  #     - "./db_data2:/var/www/html/"
  #   command: composer install

  # npm:
  #   image: "node"
  #   volumes:
  #     - "./db_data:/var/www/html/"
  #     - "./db_data2:/var/www/html/"
  #   working_dir: /var/www/html/
  #   command: bash -c 'npm install && npm run build && npm run dev'

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    links:
      - db
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    restart: always
    ports:
      - 8001:80
volumes:
  datadb:
